
services:

  wordpress:
    image: "wordpress:${WORDPRESS_VERSION}"
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define("FS_METHOD", "direct");

    env_file:
      - .env
    volumes:
      - "./versions/${WORDPRESS_VERSION}/wordpress:/var/www/html"
      - "./the-theme:/var/www/html/wp-content/themes/the-theme"

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "./versions/${WORDPRESS_VERSION}/db:/var/lib/mysql"
  adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
