
services:

  wordpress:
    image: "wordpress:${WORDPRESS_VERSION}"
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - "./versions/${WORDPRESS_VERSION}/wordpress:/var/www/html"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - "./versions/${WORDPRESS_VERSION}/db:/var/lib/mysql"
